# Generated by Django 6.0.1 on 2026-01-29 01:01

import django.db.models.deletion
import django.utils.timezone
import inventario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_ref_provider_rif_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', inventario.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='provider',
            name='rif',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='InventarioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('conciliado', 'Conciliado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('total_productos', models.IntegerField(default=0)),
                ('productos_con_diferencia', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conciliated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesion de Inventario',
                'verbose_name_plural': 'Sesiones de Inventario',
            },
        ),
        migrations.CreateModel(
            name='DetalleConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.IntegerField()),
                ('cantidad_contada', models.IntegerField()),
                ('diferencia', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.inventariosesion')),
            ],
            options={
                'verbose_name': 'Detalle de Conteo',
                'verbose_name_plural': 'Detalles de Conteo',
                'unique_together': {('sesion', 'product')},
            },
        ),
    ]
