# Generated by Django 6.0.1 on 2026-02-07 00:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_user_managers_alter_provider_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor', models.CharField(help_text='Persona o area que recibe el producto', max_length=200)),
                ('quantity', models.IntegerField()),
                ('motivo', models.TextField(help_text='Motivo o razon de la salida')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'ordering': ['-created_at'],
            },
        ),
    ]
